import { PresetProfile } from '@/lib/types';

export const PRESET_PROFILES: PresetProfile[] = [
  {
    id: 'heavy_cff_direct',
    name: 'Native Rust VM Engine (Embive & RustPython)',
    tagline: '3-Layer nested onion virtualization, Embive sandbox, Aegis CFF, RustPython runtime',
    description: 'Generates pure Python byte literals with 3 nested onion layers ending in Interpretor(globals(), b\'<bytes>\') in the same line with zero layer-revealing comments.',
    iconName: 'ShieldAlert',
    config: {
      magicNumber: '7F50564D',
      opcodeScrambling: true,
      opcodeSeed: 884721,
      opcodeRemappingMode: 'polymorphic_cascade',
      vmInstructionSet: 'polymorphic_hybrid',
      customIsaEnabled: true,
      tamperVerification: true,
      antiDebugging: true,
      heavyControlFlow: true,
      opaquePredicates: true,
      cffDegree: 'extreme_opaque',
      directBytecodeLiteral: true,
      entropyLevel: 'high',
      junkByteRatio: 0,
      payloadMultiplier: 1,
      targetOutputSizeMb: 0,
      stringEncryptionKey: 'PyShield_Master_Key_Native_2026',
      variableNameObfuscation: true,
      deadCodeInjection: false,
      supportedPythonVersions: ['3.7', '3.8', '3.9', '3.10', '3.11', '3.12', '3.13', '3.14'],
      targetArchitectures: ['x86_64', 'aarch64', 'armv7', 'riscv64', 'i686', 's390x', 'ppc64le'],
      targetOperatingSystems: ['linux', 'windows', 'darwin', 'freebsd', 'android'],
      rustVmStrategy: 'native_embedded_stub',

      // 15 Modules (Native Rust Virtual Machine Engine)
      nativeRustVirtualization: true,
      nativeCVirtualization: true,
      chunkedRamDecryption128B: true,
      masterKeystreamEncryption: true,
      polymorphicInstructionSub: true,
      machineLevelCFF: true,
      opaquePredicatesJunk: true,
      peStrippingSymbolErasure: true,
      activeKernelAntiDebug: true,
      silentMemoryCorruption: true,
      callSiteRamScrubber: true,
      hardwareExpireLock: true,
      multiOsInMemoryContainer: true,
      preVmLambdaAst: true,
      fastBitwiseMangling: true,
      antiAiPromptBombs: true,
    },
  },
  {
    id: 'heavy_bloat_7mb',
    name: 'Maximum Enterprise 7 MB Payload',
    tagline: 'Continuous 7.00 MB unsplit byte literal with polymorphic matrix',
    description: 'Expands the direct bytecode stream up to 7 MB in a single continuous byte literal to overwhelm automated analysis tools, IDA Pro, and Ghidra decompilers.',
    iconName: 'HardDrive',
    config: {
      magicNumber: '7F50564D',
      opcodeScrambling: true,
      opcodeSeed: 777123,
      opcodeRemappingMode: 'polymorphic_cascade',
      vmInstructionSet: 'polymorphic_hybrid',
      customIsaEnabled: true,
      tamperVerification: true,
      antiDebugging: true,
      heavyControlFlow: true,
      opaquePredicates: true,
      cffDegree: 'extreme_opaque',
      directBytecodeLiteral: true,
      entropyLevel: 'extreme_bloat',
      junkByteRatio: 0,
      payloadMultiplier: 7,
      targetOutputSizeMb: 7,
      stringEncryptionKey: 'PyShield_7MB_Heavy_Fortress_2026',
      variableNameObfuscation: true,
      deadCodeInjection: false,
      supportedPythonVersions: ['3.7', '3.8', '3.9', '3.10', '3.11', '3.12', '3.13', '3.14'],
      targetArchitectures: ['x86_64', 'aarch64', 'armv7', 'riscv64', 'i686', 's390x', 'ppc64le'],
      targetOperatingSystems: ['linux', 'windows', 'darwin', 'freebsd', 'android'],
      rustVmStrategy: 'native_embedded_stub',

      nativeRustVirtualization: true,
      nativeCVirtualization: true,
      chunkedRamDecryption128B: true,
      masterKeystreamEncryption: true,
      polymorphicInstructionSub: true,
      machineLevelCFF: true,
      opaquePredicatesJunk: true,
      peStrippingSymbolErasure: true,
      activeKernelAntiDebug: true,
      silentMemoryCorruption: true,
      callSiteRamScrubber: true,
      hardwareExpireLock: true,
      multiOsInMemoryContainer: true,
      preVmLambdaAst: true,
      fastBitwiseMangling: true,
      antiAiPromptBombs: true,
    },
  },
  {
    id: 'anti_ai_weapons',
    name: 'Anti-AI Prompt Bombs & Kernel Guard',
    tagline: '120+ LLM decompiler traps & hardware breakpoint scanner',
    description: 'Embeds adversarial prompt injection traps to neutralize AI-powered code analysis models alongside DR0-DR7 hardware register inspection.',
    iconName: 'Bomb',
    config: {
      magicNumber: '5059564D',
      opcodeScrambling: true,
      opcodeSeed: 492011,
      opcodeRemappingMode: 'dynamic_permutation',
      vmInstructionSet: 'polymorphic_hybrid',
      customIsaEnabled: true,
      tamperVerification: true,
      antiDebugging: true,
      heavyControlFlow: true,
      opaquePredicates: true,
      cffDegree: 'extreme_opaque',
      directBytecodeLiteral: true,
      entropyLevel: 'ultra',
      junkByteRatio: 0,
      payloadMultiplier: 1,
      targetOutputSizeMb: 1,
      stringEncryptionKey: 'Anti_AI_Weapon_Prompt_Lock_2026',
      variableNameObfuscation: true,
      deadCodeInjection: false,
      supportedPythonVersions: ['3.7', '3.8', '3.9', '3.10', '3.11', '3.12', '3.13', '3.14'],
      targetArchitectures: ['x86_64', 'aarch64', 'armv7', 'riscv64', 'i686', 's390x', 'ppc64le'],
      targetOperatingSystems: ['linux', 'windows', 'darwin', 'freebsd', 'android'],
      rustVmStrategy: 'universal_polyglot_vm',

      nativeRustVirtualization: true,
      nativeCVirtualization: true,
      chunkedRamDecryption128B: true,
      masterKeystreamEncryption: true,
      polymorphicInstructionSub: true,
      machineLevelCFF: true,
      opaquePredicatesJunk: true,
      peStrippingSymbolErasure: true,
      activeKernelAntiDebug: true,
      silentMemoryCorruption: true,
      callSiteRamScrubber: true,
      hardwareExpireLock: true,
      multiOsInMemoryContainer: true,
      preVmLambdaAst: true,
      fastBitwiseMangling: true,
      antiAiPromptBombs: true,
    },
  },
  {
    id: 'custom_magic_isa',
    name: 'Custom Magic & ISA Scrambler',
    tagline: 'Tailored for breaking decompilers (uncompyle6, pycdc, Ghidra)',
    description: 'Corrupts standard bytecode signatures with custom magic hex (0xDEADBEEF), opaque invariants, and direct raw bytecode.',
    iconName: 'Binary',
    config: {
      magicNumber: 'DEADBEEF',
      opcodeScrambling: true,
      opcodeSeed: 133742,
      opcodeRemappingMode: 'crypto_hash_table',
      vmInstructionSet: 'stack_vm',
      customIsaEnabled: true,
      tamperVerification: true,
      antiDebugging: true,
      heavyControlFlow: true,
      opaquePredicates: true,
      cffDegree: 'aggressive',
      directBytecodeLiteral: true,
      entropyLevel: 'high',
      junkByteRatio: 0,
      payloadMultiplier: 1,
      targetOutputSizeMb: 0,
      stringEncryptionKey: 'Decompile_Buster_ISA_Key',
      variableNameObfuscation: true,
      deadCodeInjection: false,
      supportedPythonVersions: ['3.7', '3.8', '3.9', '3.10', '3.11', '3.12', '3.13', '3.14'],
      targetArchitectures: ['x86_64', 'aarch64', 'armv7', 'riscv64'],
      targetOperatingSystems: ['linux', 'windows', 'darwin'],
      rustVmStrategy: 'native_embedded_stub',

      nativeRustVirtualization: true,
      nativeCVirtualization: true,
      chunkedRamDecryption128B: true,
      masterKeystreamEncryption: true,
      polymorphicInstructionSub: true,
      machineLevelCFF: true,
      opaquePredicatesJunk: true,
      peStrippingSymbolErasure: true,
      activeKernelAntiDebug: true,
      silentMemoryCorruption: true,
      callSiteRamScrubber: true,
      hardwareExpireLock: true,
      multiOsInMemoryContainer: true,
      preVmLambdaAst: true,
      fastBitwiseMangling: true,
      antiAiPromptBombs: true,
    },
  },
];
